name: day_2
description: Story application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen:
  http:
  google_fonts:
  cloud_firestore:
  firebase_auth:
  firebase_core:
  country_picker:
  pinput:
  google_sign_in:
  shared_preferences:
  provider:
  fluttertoast:
  rive:
  readmore:
  cached_network_image:
  glassmorphism:
  flutter_spinkit:
  url_launcher:
  share_plus:
  path_provider: ^2.0.11
  image_picker: ^0.8.5+3
  file_picker: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/RiveAssets/

  # example:
  fonts:
    - family: Chomsky
      fonts:
        - asset: assets/fonts/Chomsky.otf

